### ISSUE TITLE
Unit not found

### ISSUE THREAD

**Issue by landrix** [HemulGM/MaterialDesign3#1]
Hi, where can i find

GDIPCustomItem, GDIPTextItem, GDIPSectionItem,
  GDIPImageSectionItem, GDIPHeaderItem

?

**Comment by HemulGM** [comment]
This project does not require this

**Comment by landrix** [comment]
If I remove them, they will automatically added again. Who depends on it?

**Comment by landrix** [comment]
I had to remove some items that were causing crashes. Now it works.

https://github.com/landrix/MaterialDesign3/commit/a2456827200de01d3ea9cfbf980bb405f20bf231

Would you like a pull request?
